### ISSUE TITLE
SideNavItem: allow wildcards in pathAliases

### ISSUE THREAD

**Issue by sahrmann** [vaadin/hilla#2659] opened 2024-08-16 13:44 UTC
### Describe your motivation

I am using the file-based router which allows wildcards. E.g., I have the following folders/files in my folder `views`:

- authors/@index.tsx
- authors/{id}.tsx

So I can access the URL `/authors` to get a list of all authors and `/authors/3` to see the details of an author with id 3. That works fine.

Now I have a `SideNav` with a parent collapsible `SideNavItem` *Configuration* and a child `SideNavItem` *Authors* linking to `/authors`. When I select an author from the list (go to the details page `/authors/3`), the `SideNavItem` *Authors* is not activated anymore, which looks especially weird since the parent item *Configuration* is collapsed. There is no way to define a wildcard-PathAlias to keep the `SideNavItem` active.

### Describe the solution you'd like

Allow wilcards in the PathAlias like `/authors/{id}` or `/authors/*` in the `SideNavItem`.

### Describe alternatives you've considered

Workaround: Create a view `authors/detail.tsx` and put the id in a query param (`/authors/detail?id=3`). Then `authors/detail` can be used as a PathAlias and works. However, considering the design of the file based routing, this does not seem right.

**Comment by knoobie** [comment] 2024-08-16 15:07
Related to the flow issue https://github.com/vaadin/flow-components/issues/5227

**Comment by platosha** [comment] 2024-08-27 11:26
Duplicate of #5227, which is being addressed.

**Closed by platosha** 2024-08-27 11:26 UTC
Labels: enhancement, hilla
