### ISSUE TITLE
Regression: "Unexpected undefined value" is thrown when creating a Binder instance

### ISSUE THREAD

**Issue by vursen** [vaadin/hilla#919] opened 2023-04-25 08:35 UTC
### Description of the bug 

All the Vaadin docs examples using Hilla Binder have got broken since the docs switched to Vaadin 24 / Hilla 2. They now throw a JS error when attempting to create a Binder instance.

```js
private binder = new Binder(this, AppointmentModel);
```

results in:

```
Uncaught TypeError: Unexpected undefined value
    at Ve.setValueState (33956-ea330898dbb5455485e7.js:2:21704)
    at Ve.initializeValue (33956-ea330898dbb5455485e7.js:2:21353)
    at new X (33956-ea330898dbb5455485e7.js:2:17748)
    at new Ve (33956-ea330898dbb5455485e7.js:2:25524)
    at HTMLElement.value (37473-211dd31403108296fecf.js:2:8234)
    at Object.defineClassElement (37473-211dd31403108296fecf.js:2:1506)
    at Object.<anonymous> (37473-211dd31403108296fecf.js:2:1016)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (37473-211dd31403108296fecf.js:2:957)
    at Array.forEach (<anonymous>)
```

I assume it is a regression as there is no such error with Hilla 1.3.

### Minimal reproducible example

https://vaadin.com/docs/latest/components/date-picker/#custom-validation

https://vaadin.com/docs/latest/example?path=component/datepicker/date-picker-custom-validation.ts

### Versions:
    - Vaadin / Hilla version: 24.1 / 2.1
    - Node version: 18
    - Java version: 17
    - OS version: Mac OS

### Additional context

Related to https://github.com/vaadin/docs/issues/2325
Related to https://github.com/vaadin/docs/issues/2340

**Comment by cromoteca** [comment] 2023-04-25 09:57
I've copied all the Java domain classes and the related endpoint to a Hilla project and I've also copied the `date-picker-custom-validation`. I cannot reproduce the issue: the date picker is validated and shows error on weekends (although sometimes it doesn't, but without errors, so that's probably another issue). Which minor version of Hilla 2 are you using?

**Comment by vursen** [comment] 2023-04-25 09:59
> Which minor version of Hilla 2 are you using?

```xml
<!-- tag::vaadin-version[] -->
<vaadin.version>24.1.0.alpha2</vaadin.version>
<hilla.version>2.1.0.alpha2</hilla.version>
<!-- end::vaadin-version[] -->
```

https://github.com/vaadin/docs/blob/bbcebd0ae38426a18c903e6afd1304bba4411838/pom.xml#L15-L18

**Comment by cromoteca** [comment] 2023-04-25 10:14
You mentioned 2.0 in the issue, but it still works with 2.1 in my project. I'll try to run documentation.

**Comment by vursen** [comment] 2023-04-25 10:15
> You mentioned 2.0 in the issue, but it still works with 2.1 in my project. I'll try to run documentation.

Yeah, I've actually tried both 2.0 and 2.1 but the examples work in none of them.

**Comment by cromoteca** [comment] 2023-04-25 10:36
The issue is actually in the docs. Anyway, I'm going to open another issue because if you select two weekend days one after the other, the second one is not marked as error.

**Comment by vursen** [comment] 2023-04-25 10:41
> The issue is actually in the docs. 

@cromoteca Thanks for checking 🙇‍♂️

**Closed** 2023-04-26 09:14 UTC
Labels: bug, hilla, regression
