### ISSUE TITLE
Page type is ignored

### ISSUE THREAD

**Issue by simasch** [vaadin/hilla#711] opened 2022-12-30 17:47 UTC
Hilla is ignoring Page as response type.

```java
@Nonnull
public Page<@Nonnull Person> list(String filter, Pageable pageable) {
```
generates 

```typescript
function _list(
 filter: string | undefined,
 pageable: Pageable | undefined,
 __init?: EndpointRequestInit
): Promise<Array<Person>>
{
 return client.call('PersonEndpoint', 'list', {filter, pageable}, __init);
}
```
Why is that? If I would like the result as Page I cannot do that and have to create my own result type

**Comment by platosha** [comment] 2023-01-03 12:23
Duplicate of #703

**Closed by platosha** 2023-01-03 12:23 UTC
Labels: bug, hilla
