### ISSUE TITLE
Router Route animate property does not work with (vaadin-app-layout) child views 

### ISSUE THREAD

**Issue by johannest** [vaadin/hilla#201] opened 2022-02-09 12:11 UTC
### Description of the bug 
Router Route animate property does not work with (vaadin-app-layout) child views. 
### Minimal reproducible example
https://github.com/johannest/v23-hilla-animate
### Expected behavior
When navigating between Home and About views, the transition animation (fade) should be shown.
### Actual behavior
No animation is shown
### Versions:
    - Vaadin / Hilla version: V22.0.4 and Hilla 1.0.0.beta1 tested
    - Node version: v16.14.0 and v14.17.0 tested 
    - Java version: 11.0.13
    - OS version: Win 11 and Ubuntu 20.04.3 LTS tested
    - Browser version (if applicable): at least Chrome

**Comment by valentin-ricard** [comment] 2022-02-09 12:46
Can reproduce with any child view (does not work with a custom one) on both firefox and chrome on vaadin v22.0.0-5

**Comment by haijian-vaadin** [comment] 2022-02-10 12:29
Seems that it turns out to be a CSS issue in the application. With the `>` selector, it only selects the direct child. Could you apply this change and see if it works for you?
![image](https://user-images.githubusercontent.com/30408303/153408769-9c1b72ab-6116-482d-a269-95d5e38369ee.png)

**Comment by valentin-ricard** [comment] 2022-02-10 12:43
This fixes in part the problem (now navigating between hilla defined routes works), but navigating between two flow defined routes (using Router.go) with `serverSideRoutes` does not work.

From my testing, it seems because serverSideRoutes is seen in the routes variable as only a single route, not animating between them.

**Comment by valentin-ricard** [comment] 2022-02-10 15:17
That explains everything then

Thanks for the pointer, I will try using the add-on you recommended, or making an alternative for this specific case only (triggering the hilla animation when changing flow routes)

Thanks for the quick response and have a great day!

**Comment by haijian-vaadin** [comment] 2022-02-11 07:28
Thank you, then I would like to close this ticket, as it's not a bug in Router.

**Closed by haijian-vaadin** 2022-02-11 07:28 UTC
Labels: bug, hilla, BFP
