### ISSUE TITLE
Hilla support for Spring Initializr

### ISSUE THREAD

**Issue by cromoteca** [vaadin/hilla#957] opened 2023-05-16 11:52 UTC
Let's create a PR for Spring Initializr to add Hilla support.

There's already one which has been merged and then reverted, but it was incomplete.

**Comment by tarekoraby** [comment] 2023-05-16 13:03
Duplicate of #956?

**Comment by platosha** [comment] 2023-05-24 10:56
#956 is an umbrella epic, this one is a part of it about making the PR.

**Closed** 2023-07-26 12:53 UTC
Labels: enhancement, hilla
