### ISSUE TITLE
Multimodule Engine Compiler not called on Hilla 2.0

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#836] opened 2023-03-13 22:19 UTC
### Description of the bug 

I like to use the Multi Module Feature with Hilla 2.0. But when I start the example project "[hilla-multi-module](https://github.com/vaadin/hilla-multi-module)" it does not call the ts generator with the multi engine although the property file and experimental feature has been enabled. As a result the Endpoint "HelloWorld" get not found by the TSC during the start of the application.

The original example project on Github "[hilla-multi-module](https://github.com/vaadin/hilla-multi-module)" with Hilla 1.2.2 works fine. You can test this by omitting step 4 from the description below.

### Minimal reproducible example
1. Download or clone [hilla-multi-module](https://github.com/vaadin/hilla-multi-module)
2. cd hilla-multi-module
3. add the file "vaadin-featureflags.properties" with the multi module engine flag activated into "application/src/main/resources/vaadin-featureflags.properties"
4. Update the two POM files to make use of hilla 2.0 and spring boot 3
6. mvn -U clean install
7. cd application 
8. mvnw

*application/src/main/resources/vaadin-featureflags.properties*
```
com.vaadin.experimental.viteForFrontendBuild=true
com.vaadin.experimental.hillaEngine=true
```
*/application/pom.xml*
```
...
    <properties>
        <java.version>17</java.version>
        <hilla.version>2.0.0</hilla.version>
        <selenium.version>4.8.1</selenium.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.4</version>
        <relativePath/>
    </parent>
...
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>dev.hilla</groupId>
                <artifactId>hilla-bom</artifactId>
                <version>${hilla.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
```
*/library/pom.xml*
```
...
    <dependencies>
        <dependency>
            <groupId>dev.hilla</groupId>
            <artifactId>hilla</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>
...
```

### Expected behavior
During the start with "mvnw"  the application should activate the multi module feature by showing at the command line / console the following output, but it doesn't. As a consequence the endpoints from the dependent maven module get not generated and later in the hellow-world-view.ts not found.  
```
The following EXPERIMENTAL features are enabled:
- Multi-module engine in Hilla
```
### Actual behavior
The following error get created because the endpoint get not generated by the multi module engine
```
2023-03-13T22:39:57.047+01:00  INFO 3172 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :  ERROR(TypeScript)  Cannot find module 'Frontend/generated/HelloWorldEndpoint' or its corresponding type declarations.
``` 
![image](https://user-images.githubusercontent.com/7382336/224844830-fd4966ae-5691-40fc-a1dd-122b16aeef67.png)

### Versions:
    - Vaadin / Hilla version: 2.0.0
    - Node version:  v18.14.2
    - NPM version:  v9.5.0
    - Java version: 17
    - OS version: Windows 11
    - Browser version (if applicable): FireFox
    - Application Server (if applicable): Embedded Tomcat from Spring Boot 3

**Comment by taefi** [comment] 2023-04-26 13:25
I investigated this a bit, and it seems that the problem is not about the engine is not called, it is actually called, but according [this documentation](https://hilla.dev/docs/react/reference/configuration#multi-module-projects-or-external-dependency-endpoints), the parser is not looking into jar files by default, and since the `HelloWorldEndpoint` is located inside the `library-1.0-SNAPSHOT.jar` it cannot find it. 

The workaround is to expose the `com.example.application` as explained in the mentioned documentation.

**Comment by taefi** [comment] 2023-04-26 14:40
@egloffmark Thanks for trying the multi-module feature with Hilla 2.x version and reporting this issue. 
The example project is updated now, and it working by exposing the packages containing endpoints (see the above comment).

The `NonnullPlugin` overriding part seems to have a problem that is not necessarily related to this issue, so the configuration part is removed and now the project should be working. 

That problem with the plugin overriding is reported here: https://github.com/vaadin/hilla/issues/923

I'm closing this issue, but please give it a try and feel free to reopen in case of having problems.

**Closed by taefi** 2023-04-26 14:40 UTC
Labels: bug, hilla, Severity: Major, Impact: Low
