### ISSUE TITLE
@hilla/react-form is not installed

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1199] opened 2023-09-01 11:35 UTC
### Actual behavior
```
npx @hilla/cli init --pre --react hillou
cd hillou
npx upgrade-vaadin 2.2.0.alpha11
mvn
grep react-form package.json
```

### Versions:
    - Vaadin / Hilla version: 2.2.0.alpha11

**Comment by platosha** [comment] 2023-09-01 13:13
Duplicate of #1181

**Closed by platosha** 2023-09-01 13:13 UTC
Labels: bug, hilla
