### ISSUE TITLE
The headerRenderer is ignored when using GridSortColumn

### ISSUE THREAD

**Issue by johannest** [vaadin/hilla#1097] opened 2023-07-11 07:05 UTC
### Description of the bug 
The headerRenderer seems to work only for standard GridColumn, but is ignored when using GridSortColumn
### Minimal reproducible example
```
<Grid items={people}>
              <GridColumn path="id" headerRenderer={() => {
                  return <div>TestHeader1</div>
              }}
              />
              <GridSortColumn path="name"
                              headerRenderer={() => {
                                  return <div>TestHeader2</div>
                              }}
              />
          </Grid>
```
### Expected behavior
The headerRenderer would work also for GridSortColumn.
### Actual behavior
The column name is got from the path instead of headerRenderer:
![image](https://github.com/vaadin/hilla/assets/2297689/c67f1773-6eb6-48b5-a935-7f041395c239)

### Versions:
    - Vaadin / Hilla version: 2.0.6, 2.1.2
    - Node version: v20.3.1
    - Java version: 19
    - OS version: MacOS
    - Browser version Chrome
    - IDE/Editor (if applicable): IntelliJ IDEA

**Comment by web-padawan** [comment] 2023-07-11 07:22
Thanks for the issue. The current behavior is by design - see [the comment](https://github.com/vaadin/web-components/blob/c2421a9017d3f90b493c28cefd18b6d56c500222/packages/grid/src/vaadin-grid-sort-column.js#L79-L87) in the code about using default header renderer.

**Comment by cromoteca** [comment] 2023-07-25 11:41
Closing in favor of https://github.com/vaadin/react-components/issues/130.

**Closed by cromoteca** 2023-07-25 11:41 UTC
Labels: enhancement, hilla
