### ISSUE TITLE
hillaI18n Feature flags for experimental features is ignored in production mode

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/hilla#2750] opened 2024-09-20 10:02 UTC
### Describe the bug

This issue is still happening in Vaadin 24.4.12 and Vaadin 24.5.0.beta1.

https://github.com/vaadin/hilla/issues/2637

> I have a file vaadin-featureflags.properties which contains com.vaadin.experimental.hillaI18n=true. In my local environment, the i18n-instance can be used without problems. However, in my production build, the frontend crashes with the error The Hilla I18n API is currently considered experimental and may change in the future. To use it you need to explicitly enable it in Copilot or by adding com.vaadin.experimental.hillaI18n=true to vaadin-featureflags.properties.

### Reproduction

https://github.com/jcgueriaud1/spring-petclinic-vaadin-flow/tree/hilla

Build and run the application in production mode

### System Info

Vaadin 24.4.12 and Vaadin 24.5.0.beta1

**Comment by platosha** [comment] 2024-09-24 11:13
Last time this was caused by using a wrong class loader when generating feature flags TypeScript values in production build.

**Comment by cromoteca** [comment] 2024-10-21 12:03
Fixed in `24.6` by https://github.com/vaadin/platform/pull/6897, cherry-picked to `24.5` and `24.4`. It will be included in the next patch releases.

**Comment by jcgueriaud1** [comment] 2024-10-24 10:27
Fixed in 24.5.1

**Comment by sveinnetnordic** [comment] 2024-10-24 19:48
Works for me :-)

**Closed** 2024-10-30 11:05 UTC
Labels: bug, hilla, Severity: Blocker, Impact: High, BFP

**Comment by cromoteca** [comment] 2024-10-30 11:06
Released in `24.5.1` and `24.4.16`.
