### ISSUE TITLE
FluxConnection atmosphere-websocket long-polling fallback not always best option

### ISSUE THREAD

**Issue by cproinger** [vaadin/hilla#1830] opened 2023-11-29 16:03 UTC
### Describe your motivation

in the file node_modules/@hilla/frontend/FluxConnection.js i see that the websocket connection created via atmosphere with the setting for fallbackTransport as 'long-polling'. This leads to the situation that if a user loses its network connection for a short period, subsequently the FluxConnection relies solely on long-polling after that. i can see that in our monitoring solution. 

### Describe the solution you'd like

I'm not familiar with the details of how atmosphere.js can be configured. either the FluxConnection should somehow switch back to websocket or just don't use long-polling as a fallback. at least i would like to have the configuration-option if that does not make sense as as default. 

additionally. we would need the fix for hilla 1.3

**Comment by platosha** [comment] 2023-12-11 15:25
While improving configuration or defaults is a possible way to go about this issue, we should address primarily that the clients end up relying only on long-polling after network disruptions. This could be considered as a bug.

**Comment by Artur-** [comment] 2023-12-15 08:23
Do you have a proxy or something else between the browser and the server? Losing network connection, going offline or similar is not supposed to change to the fallback transport but if the server (or a proxy) refuses a websocket connection in one way or another, then Atmosphere will likely fall back to long polling

**Comment by cproinger** [comment] 2023-12-15 11:47
> Do you have a proxy or something else between the browser and the server? Losing network connection, going offline or similar is not supposed to change to the fallback transport but if the server (or a proxy) refuses a websocket connection in one way or another, then Atmosphere will likely fall back to long polling

yes we do have a reverse proxy in our real environment. i will investigate if that could be the source of that behaviour. 

on another note. even on our development-machines were we don't use a reverse-proxy, we get the behavior that if we have a flux-subscription and we use chrome-dev-tools to set the network throttling to "offline", we do not get any new messages even if we set the network throttling back to "online".

**Comment by cromoteca** [comment] 2023-12-15 15:21
Let me share my findings about this issue.

The `fallbackTransport` is not directly related to reconnection. It sets the strategy used when websockets are not available. I wasn't able to replicate a scenario that falls back to long polling just because of a connection loss.

Reconnection is not implemented by default, see https://github.com/vaadin/hilla/issues/398. Some implementation examples are provided in that issue.

Setting throttling to offline actually disconnects from the flux. If you want to reconnect after the application has going offline, this should be implemented manually at the moment (see issue above).

On the contrary, if the network issue happens along the wire, the reconnection then happens correctly and the lost messages are transmitted to the client. To test this scenario, I run the application in production mode in a VM, and then I connect to that VM. This allows to better simulate network problems by putting the VM online instead of the browser. In this case, the application doesn't go offline, but cannot connect during the simulated outage.

All these tests have been performed with both Hilla 1.3.30 and 2.5.1.

**Comment by cromoteca** [comment] 2023-12-18 09:58
@cproinger if a real network connection problem happens, Hilla is already able to reconnect to the websocket, provided that it has not been closed for timeout. Is that enough for your needs? Putting the browser offline is different, since it causes disconnection by design.

**Comment by cproinger** [comment] 2024-01-15 09:47
> @cproinger if a real network connection problem happens, Hilla is already able to reconnect to the websocket, provided that it has not been closed for timeout. Is that enough for your needs? Putting the browser offline is different, since it causes disconnection by design.

sorry for the late reply. unfortunately i did not have time to investigate this further and it could be a while until i can. 

our customization currently does seem to be good enough.

**Comment by cromoteca** [comment] 2024-01-29 15:18
@cproinger thanks to https://github.com/vaadin/hilla/pull/1959 (cherry-picked in https://github.com/vaadin/hilla/pull/1984), you can now amend the Atmosphere configuration by defining your own `connect-client.js` file.

Closing as this should allow to apply the needed customization, feel free to reopen the issue if needed.

**Closed by cromoteca** 2024-01-29 15:18 UTC
Labels: bug, hilla, Severity: Major, Impact: High, BFP
