### ISSUE TITLE
IntelliJ causes project to reload excessively 

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/hilla#1309] opened 2023-09-18 22:42 UTC
IntelliJ IDEA 2023.2 Ultimate. Hilla 2.2.0.

I have two (seemingly related) issues when developing with IntelliJ. 

1. When I start a newly created app, it ends up with a 500 error because IntelliJ copies resources during the startup, causing IOExceptions when trying to delete folders under `node_modules`. After a while, the build recovers and the app works.
2. When I'm developing and blur the IDE window by switching to the browser after a code change, IntelliJ again copies resources causing a second reload. 

In both cases, the changed files seem to be these:
```
2023-09-18T15:33:52.043-07:00  INFO 75918 --- [   File Watcher] rtingClassPathChangeChangedEventListener : Restarting due to 7 class path changes (0 additions, 0 deletions, 7 modifications)
2023-09-18T15:33:52.044-07:00 DEBUG 75918 --- [   File Watcher] rtingClassPathChangeChangedEventListener : Change set: [/Users/mhellber/Desktop/crm/target/classes [/Users/mhellber/Desktop/crm/target/classes/META-INF/resources/images/empty-plant.png (MODIFY), /Users/mhellber/Desktop/crm/target/classes/META-INF/resources/icons/icon.png (MODIFY), /Users/mhellber/Desktop/crm/target/classes/banner.txt (MODIFY), /Users/mhellber/Desktop/crm/target/classes/vaadin-featureflags.properties (MODIFY), /Users/mhellber/Desktop/crm/target/classes/com/example/application/Application.class (MODIFY), /Users/mhellber/Desktop/crm/target/classes/com/example/application/services/package-info.class (MODIFY), /Users/mhellber/Desktop/crm/target/classes/application.properties (MODIFY)]]
```

I do not have "Build project automatically" enabled in IntelliJ.

**Comment by marcushellberg** [comment] 2023-09-18 23:36
I found the culprit after a lot of digging around. By default, IntelliJ run configurations have "Update classes and resources" on frame deactivation enabled for run configurations. Disabling it solves the issue. 

<img width="1152" alt="idea-go-boom-boom" src="https://github.com/vaadin/hilla/assets/883698/6d59b4d6-92f7-49e3-bd6c-1c6ae0165acf">

But the issue remains that the default setting of running a Hilla app in IntelliJ is more or less broken. Is there anything we can do to fix it?

**Comment by marcushellberg** [comment] 2023-09-19 00:25
The change happened here https://youtrack.jetbrains.com/issue/IDEA-321478/Spring-Boot-enable-Update-actions-automatically-in-new-run-configurations-if-dev-tools-present

**Comment by taefi** [comment] 2023-09-22 12:37
This issue seems to exist with Flow `24.2.0.alpha9` as well, but not with Flow `24.2-SNAPSHOT`. 
The [Caching for Spring Boot DevTools reload](https://github.com/vaadin/flow/pull/17621) and some other seems to have something to do with resolving this issue as well. @marcushellberg could you override the flow version in your environment and see if it is fixing the issue?

```xml
 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>flow-bom</artifactId>
                <version>24.2-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>dev.hilla</groupId>
                <artifactId>hilla-bom</artifactId>
                <version>${hilla.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by marcushellberg** [comment] 2023-10-15 22:26
Which version should I test with?

**Comment by cromoteca** [comment] 2023-10-16 06:09
I used the latest beta: `2.3.0.beta1`.

**Comment by marcushellberg** [comment] 2023-10-17 16:39
It still does an extra reload on frame deactivation unless you remove that setting in intellij

**Comment by marcushellberg** [comment] 2023-10-18 20:36
I can also confirm that the 500 error is occurring with 2.3.0.rc1

<img width="1272" alt="Screenshot 2023-10-18 at 13 35 18" src="https://github.com/vaadin/hilla/assets/883698/5aa5fb3b-fa12-4fe5-8a88-b925ab197830">

**Comment by cromoteca** [comment] 2023-10-19 15:30
I cannot reproduce any of those. I'm using RC1 now and I see no error in the page. Also, continuously switching windows makes a rapid build message appear in the IDEA status bar, but with no consequences in the Hilla application.

**Comment by marcushellberg** [comment] 2023-10-24 05:23
I'm still consistently running into the 500 error on startup with new projects if I forget to remove the frame deactivation build. Today, with 2.3.1.

**Comment by taefi** [comment] 2023-12-15 09:34
I can confirm that vaadin/flow#18018 fixed the issue, and the lock file prevents parallel runs in IntelliJ when the frame deactivation option is active in the run configurations. In case of having multiple frame deactivations (which leads to having multiple hot restarts by spring-boot-devtools), there might be error logs complaining about the application instance already stopped or etc., but it doesn't prevent the application from a normal startup.

@marcushellberg Could you also check to see whether you still experience the same in Hilla `2.5.1` (Vaadin 24.3.0), before closing this issue?

**Closed** 2023-12-21 12:43 UTC
Labels: bug, hilla, Severity: Blocker, Impact: High
