### ISSUE TITLE
Project generated with Hilla CLI using flags --empty and --next starts with warning/error

### ISSUE THREAD

**Issue by rbrki07** [vaadin/hilla#2287] opened 2024-04-03 09:37 UTC
### Describe the bug

A new Hilla project created with the Hilla CLI using the flags `--empty` and `--next` starts with the following warning/error:
```
------------------ Starting Frontend compilation. ------------------
2024-04-03T11:33:23.465+02:00  INFO 14934 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Running Vite to compile frontend resources. This may take a moment, please stand by...
2024-04-03T11:33:25.527+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : The directory of route files: file:///Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/views/
2024-04-03T11:33:25.527+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : The directory of generated files: file:///Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/generated/
2024-04-03T11:33:25.527+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : The output directory: file:///Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/target/classes/META-INF/VAADIN/webapp
2024-04-03T11:33:25.545+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error: ENOENT: no such file or directory, opendir '/Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/views/'
2024-04-03T11:33:25.569+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2024-04-03T11:33:25.569+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   VITE v5.2.6  ready in 2038 ms

----------------- Frontend compiled successfully. -----------------

2024-04-03T11:33:25.569+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2024-04-03T11:33:25.569+02:00  INFO 14934 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Started Vite. Time: 4195ms
2024-04-03T11:33:25.570+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   ➜  Local:   http://127.0.0.1:51401/VAADIN/
2024-04-03T11:33:25.816+02:00  WARN 14934 --- [nio-8080-exec-2] .r.RouteUnifyingIndexHtmlRequestListener : Failed to find views.json under /Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/generated
2024-04-03T11:33:29.175+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 
2024-04-03T11:33:29.175+02:00  INFO 14934 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [TypeScript] Found 0 errors. Watching for file changes.
```

The following error is shown on log-level info:
```
Error: ENOENT: no such file or directory, opendir '/Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/views/'
```

The following warning is shown:
```
Failed to find views.json under /Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/generated
```

### Expected-behavior

A new Hilla project created with the Hilla CLI using the flags `--empty` and `--next` should start without warnings/errors.

### Reproduction

```shell
npx @hilla/cli init --next --empty hilla-project-with-pre-release-no-menu-and-one-empty-view
cd hilla-project-with-pre-release-no-menu-and-one-empty-view
./mvnw
```

### System Info

Hilla: 24.4.0.alpha18
Hilla CLI: 2.0.1
Java: 21.0.2
OS: macOS Sonoma 14.4.1 (23E224)

**Comment by Legioth** [comment] 2024-04-03 10:01
The `Error: ENOENT` message seems to be caused by the new Vite plugin for the file system router assuming that a `views/` directory always exists. We should probably just update the logic to gracefully deal with completely empty projects.

The warning was fixed just moments ago through https://github.com/vaadin/hilla/issues/2281 but the fix is not yet released.

**Comment by rbrki07** [comment] 2024-04-03 10:37
Thank you, @Legioth. I searched for similar issues, but I obviously overlooked #2281. I'll close this issue.

**Comment by Legioth** [comment] 2024-04-03 11:15
Should still keep this issue open to track the fix for the `Error: ENOENT` message.

**Comment by rbrki07** [comment] 2024-04-05 07:52
I can confirm that 
```
Failed to find views.json under /Users/rwilby/Documents/workspaces/hilla/hilla-project-with-pre-release-no-menu-and-one-empty-view/src/main/frontend/generated
```
is no longer shown, when I use the latest Alpha-Release.

Regarding the `Error: ENOENT` message: I think this is related to #2196.

**Comment by Legioth** [comment] 2024-04-05 08:23
Nice find. I guess we can close this one then in favor of https://github.com/vaadin/hilla/issues/2196.

**Closed by Legioth** 2024-04-05 08:23 UTC
Labels: bug, hilla
