### ISSUE TITLE
Brotli mode seems not to work when omitting the file hashing

### ISSUE THREAD

**Issue by egloffmark** [vaadin/hilla#829] opened 2023-03-11 12:00 UTC
Dear all I created a standard my-hilla app based from the hilla-cli template "npx @hilla/cli init my-hilla-app" and built it for production mode as single jar file. The brotli *.br files get created. When I now start the application from Jar file with normal java and passing the "-Dvaadin.brotli=true" parameter, it seems that the embedded Tomcat does not recognize this and just sends the normal html and js files.

Did I made something wrong?

See also https://vaadin.com/docs/latest/configuration/properties

1. npx @hilla/cli init my-hilla-app
2. omit the hashing of the files by adding in "vite.config.ts"  the "rollupOptions.output" (see below in the discussion)
3. mvn build for prod `mvn clean package -P production`
4. run spring boot application from jar with brotli  

`java -Dvaadin.brotli=true -Dvaadin.productionMode=true -jar my-hilla-app-1.0-SNAPSHOT.jar`

![image](https://user-images.githubusercontent.com/7382336/224483136-1586e869-77da-46fe-ab8c-b6180ef00f7a.png)

**Comment by Artur-** [comment] 2023-03-11 12:11
How do you see that it is not using the Brotli files?

To me it looks like it does use them
![image](https://user-images.githubusercontent.com/260340/224483652-219ec100-4947-4567-af7f-bc408297d89c.png)

**Comment by egloffmark** [comment] 2023-03-11 13:09
I see in my chrome only the *.js file and size from the JS file. May be I interpret the network traffic from Chrome wrong?

![image](https://user-images.githubusercontent.com/7382336/224486438-1550f2c7-1992-48a1-b68d-7efaeefcb4d7.png)

**Comment by Artur-** [comment] 2023-03-11 13:11
You need to hover it to see the transferred size or click on it to see if content-encoding was br. The size shown in the grid is the resource size, uncompressed

**Comment by egloffmark** [comment] 2023-03-11 13:14
Yes it says there the same size

![Selection_062](https://user-images.githubusercontent.com/7382336/224486678-757beffd-117e-4f03-bba2-6b2b6e0779af.png)

**Comment by Artur-** [comment] 2023-03-11 13:22
Well isn't that odd. Care to share the project?

**Comment by egloffmark** [comment] 2023-03-11 13:26
Ok found the issue, seems to be related that I omit the "hashcoding" of the file. However the strange thing is that the "brotli" files get created. so not sure if it is "hilla" problem or may be a "vite" issue.

in "vite.config.ts":

```
import { UserConfigFn } from 'vite';
import { overrideVaadinConfig } from './vite.generated';

const customConfig: UserConfigFn = (env) => ({
  // Here you can add custom Vite parameters
  // https://vitejs.dev/config/
  	build: {
		minify: "terser",
	terserOptions: {
		parse: {
		html5_comments: false,
		},
		output: {comments: false}
	},
    rollupOptions: {
	output: {
        entryFileNames: `assets/[name].js`,
        chunkFileNames: `assets/[name].js`,
        assetFileNames: `assets/[name].[ext]`
    }
		  
   }
   },
});

**Comment by Artur-** [comment] 2023-03-11 14:03
Vaadin serves the Brotli files and I think the problem is not hashing but that it expects the files to be inside VAADIN/build

**Comment by egloffmark** [comment] 2023-03-11 14:13
Ok so the mapping in my "rollupOptions.output" in "vite.config.ts"  is wrong ands should be consider the right directory path "VAADIN/build".

After that it works as expected. Thank you ! 

You can close the issue.

```
import { UserConfigFn } from 'vite';
import { overrideVaadinConfig } from './vite.generated';

import minifyHTML from 'rollup-plugin-minify-html-literals';


const customConfig: UserConfigFn = (env) => ({
  // Here you can add custom Vite parameters
  // https://vitejs.dev/config/
  	build: {
		minify: "terser",
	terserOptions: {
		parse: {
		html5_comments: false,
		},
		output: {comments: false}
	},
    rollupOptions: {
	output: {
        entryFileNames: `VAADIN/build/[name].js`,
        chunkFileNames: `VAADIN/build/[name].js`,
        assetFileNames: `VAADIN/build/[name].[ext]`
   }	  
   }
   },
});

export default overrideVaadinConfig(customConfig);
```
![image](https://user-images.githubusercontent.com/7382336/224489479-9d5069a5-232a-4331-bc6f-4e3d18090c68.png)

**Closed** 2023-03-11 14:17 UTC
Labels: bug, hilla
