### ISSUE TITLE
The quickstart tutorial project does not work with Hilla 1.0.5

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#385] opened 2022-04-13 06:32 UTC
```
npx @vaadin/cli init --preset hilla-quickstart-tutorial hilla-grocery-app
cd hilla-grocery-app
mvn
```

Shows a white page in the browser and
```
Uncaught SyntaxError: The requested module '/VAADIN/@fs/<path-to-project>/hilla-grocery-app/node_modules/lit/index.js?v=34983637' does not provide an export named 'LitElement' (at lit-mobx.ts:14:1)
```

**Comment by tarekoraby** [comment] 2022-04-13 06:39
I cannot reproduce this.

**Comment by platosha** [comment] 2022-04-26 11:04
The issue is related with `@vaadin/bundles`, fixed in 23.0.6.

**Closed by platosha** 2022-04-26 11:04 UTC
Labels: bug, hilla
