### ISSUE TITLE
Internal server error: [postcss]

### ISSUE THREAD

**Issue by simasch** [vaadin/hilla#696] opened 2022-12-19 17:31 UTC
I created a new React Hill app:

    npx @hilla/cli init --react my-hilla-app

**When I start it directly from IntelliJ I get this error in the console:**

```
2022-12-19 18:27:58.941  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :   File: c:/Users/simon/Workspace/react/my-hilla-app/frontend/views/MainLayout.module.css:undefined:undefined
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at new FileSystemLoader (file:///c:/Users/simon/Workspace/react/my-hilla-app/node_modules/vite/dist/node/chunks/dep-2e4b3d45.js:1582:15)
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at getLoader (file:///c:/Users/simon/Workspace/react/my-hilla-app/node_modules/vite/dist/node/chunks/dep-2e4b3d45.js:7409:79)
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at OnceExit (file:///c:/Users/simon/Workspace/react/my-hilla-app/node_modules/vite/dist/node/chunks/dep-2e4b3d45.js:7463:22)
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at LazyResult.runAsync (c:\Users\simon\Workspace\react\my-hilla-app\node_modules\postcss\lib\lazy-result.js:433:21)
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at LazyResult.async (c:\Users\simon\Workspace\react\my-hilla-app\node_modules\postcss\lib\lazy-result.js:221:30)
2022-12-19 18:27:58.942  INFO 35616 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :       at LazyResult.then (c:\Users\simon\Workspace\react\my-hilla-app\node_modules\postcss\lib\lazy-result.js:206:17)

```

And the application doesn't start

![image](https://user-images.githubusercontent.com/593352/208485166-1ed973f8-c320-4a64-9150-522155d7b631.png)

**As I found out the error happens because the hilla plugin prepare-frontend didn't run!**

**Comment by platosha** [comment] 2022-12-20 09:12
We’re unable to reproduce. This seems to be caused by the bug in `postcss-modules` https://github.com/madyankin/postcss-modules/issues/140, which is built into Vite.

The recent version of Vite should already have the fix, let us update and see if it helps.

**Comment by simasch** [comment] 2022-12-20 09:17
And you did it exaclty like this:

1. npx @hilla/cli init --react my-hilla-app
2. Open the project in IntelliJ 
3. Run it from IntelliJ 
Important DO NOT use Maven!

**Comment by Artur-** [comment] 2022-12-20 09:37
The mentioned PR is fixed in postcss-modules 6, Vite 3.2.4 uses postcss 5

**Comment by platosha** [comment] 2023-01-02 08:51
The master in Flow uses Vite v4.0.3, where the issue is fixed already.

The 23.3 Flow branch is using Vite v3.2.4, which could be upgraded to v3.2.5 that also has the fix.

**Comment by platosha** [comment] 2023-01-03 08:31
should be fixed by https://github.com/vaadin/flow/pull/15603

**Closed by platosha** 2023-01-03 08:31 UTC
Labels: bug, hilla
